name: Cross Build and Release

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            executable-name: cobrinha
            target: x86_64-unknown-linux-gnu

          - os-name: Linux-aarch64-macOS
            runs-on: ubuntu-24.04
            executable-name: cobrinha
            target: aarch64-unknown-linux-gnu

          - os-name: Windows-x87_64
            runs-on: ubuntu-24.04
            executable-name: cobrinha.exe
            target: x86_64-pc-windows-gnu

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: build
        run: cross build --release --locked --target ${{ matrix.platform.target }}
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ${{ matrix.platform.executable-name }}
          target: ${{ matrix.platform.target }}
