name: Cross Build and Release

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            install-deps: sudo apt install pkg-config libx11-dev libxcb1-dev libxext-dev libxi-dev libxtst-dev
            target: x86_64-unknown-linux-gnu

          # - os-name: Linux-aarch64
          #   runs-on: ubuntu-24.04
          #   install-deps: sudo apt install pkg-config libx11-dev gcc-multilib
          #   target: aarch64-unknown-linux-musl
          #
          # - os-name: Windows-x86_64
          #   runs-on: windows-latest
          #   install-deps: echo Windows
          #   target: x86_64-pc-windows-msvc
          #
          # - os-name: macOS-x86_64
          #   runs-on: macOS-latest
          #   install-deps: echo maaaac
          #   target: x86_64-apple-darwin
          #
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: ${{ matrix.platform.install-deps }}
      #- name: Install cross
      #  run: cargo install cross --git https://github.com/cross-rs/cross
      - name: build
        run: cargo build --release --locked --target ${{ matrix.platform.target }}
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ubi
          target: ${{ matrix.platform.target }}
